sonar.projectKey=biosensor
sonar.projectName=BioSensorProject
sonar.projectVersion=1.0

sonar.sources=lib
sonar.tests=test
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.token=sqp_653477e623e6c2bdc97c96fa3f9c5f238aff03ad

sonar.exclusions=**/build/**,**/.dart_tool/**,**/android/**,**/ios/**
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-


